### ISSUE TITLE
Epic: Journeys iOS

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#105]
This is an epic for journey related stories.

parent of #106 (create journey)
parent of #107 (add a flight to journey)
parent of #108 (add an order to a journey)
parent of #110 (add a wishlist item to journey)
parent of #109 (remove from journey)
parent of #111 (view list of journeys)
parent of  #112 (view a journey)

Future:
parent of (share a journey)
auto create journey based on auto grouping of items
auto add wishlist items and propose traveler buys them
auto add items in cart and propose traveler buys them
auto add items from orders

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
