### ISSUE TITLE
Create journey

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#106]
As a traveler, I can create a journey so that I can group multiple items from various catalogs and flights together to represent a trip in one place.

**Acceptance Criteria**
1. Should be able to name the journey. Propose format: destination and date range, eg. Dallas Feb 4-16 2019.
2. If a journey by this name exists, propose to add a differentiator, e.g. Dallas trip vs Dallas trip new.

**Future Consideration**
Application should be smart enough to know that some items could be grouped together and propose the grouping and a new journey to be created around them to the traveler. The grouping would be based on location and timeframes. If we know of a flight, it automatically warrants a journey to be created. If we know that flight has connecting flights based on timing and locations, these get added to the same journey. The flight that has the latest destination date/time wise and is not repeated yet is proposed as the name of the journey. Any catalog (experience, BOB or services) that has same date/timeframe and locations is automatically proposed to be grouped as well.

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
