### ISSUE TITLE
Add a flight to journey

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#107]
As a traveler, I can add a flight to a journey that I've already created or to a new journey, so that I can keep track of it and other items on itinerary for that trip.

**Acceptance Criteria**
Traveler should be able to do this from newly added flight or from a list of flights that they have

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
