### ISSUE TITLE
Add an order to a journey

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#108]
As a traveler, I add an order to a journey either already created or to a new journey, so that I can keep track of things I plan to do on my trip.

**Acceptance Criteria**
The traveler should be presented with this option right after completing an order.

The traveler should also be able to do this from the list of orders and when viewing an individual order.

The traveler should be able to do this from the journey itself and specify what order to add to it.

**Future Considerations**
The application would suggest which journey to add the order to.

The traveler would be able to add an individual item from the order to the journey.

The user should be able to pick which items of the order are added to which journeys

The user should be able to add not only experience items but BOB and services items as well.

**Error messages:**
If something goes wrong on the adding of the item to the journey, the traveller should be able to retry.

Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
