### ISSUE TITLE
Remove item from journey

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#109]
As a traveler, I remove an item from a journey that I added erroneously or do not want to see in my journey.

**Acceptance Criteria**
Should be able to do this with any item: flight, order (any catalog item, experience/BoB/service)

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
