### ISSUE TITLE
Add a wishlist item to a journey

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#110]
As a traveler, I add a wishlist item to a journey so that I can see where it fits and how cluttered the itinerary for the journey is becoming.

**Acceptance Criteria**
Should be able to do this from viewing wishlist and its items.
Should be able to do this from viewing the wishlist item (currently the experience catalog detail item page only).

**Future Considerations**
The adding of a wishlist item into a journey would be automatic whenever possible (assuming the application can discern which journey to add the wishlist item to)

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
