### ISSUE TITLE
View list of journeys

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#111]
As a traveler, I view the list of journeys I currently have, so that I can manage my journeys.

**Acceptance Criteria**
The traveler should be able to drill down into a detail view of a given journey or delete a journey or create a brand new journey while looking at the list.
The journeys should be listed in chronological order based on their date start. If there are two journeys that have the same date start, look at the time start. If both are the same, resort to listing journey alphabetically (aka if two journeys start at same date and time, list them in alphabetical order).
Will need to be able to see past journeys vs upcoming journeys. In both groups, should be able to see the journeys spanning 1 month, 3 months and 6+ months away from today (into future or past).

**Future Considerations**
Ability to search by a name of a journey

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
