### ISSUE TITLE
View a journey

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#112]
As a traveler, I can look at a specific journey, so that I can get details on what is included in this journey and plan my trip accordingly. 

**Acceptance Criteria**
The items in the journey should be listed chronologically.

I should be able to filter to see all or some of the following groups: 
-flights 
-categories of experience catalog 
-BOB catalog items
-services

I should be able to toggle between wishlist vs bought items.

**Future Considerations**
What has been considered and is currently out of scope but may be implemented later on through a different user story/epic.

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
