### ISSUE TITLE
Email confirmation on submitting the order

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#113]
As a traveler, I receive an email notification stating details of my order, so that I have proof of placing the order regardless of whether I have profile.

**Acceptance Criteria**

If the content is bookable (e.g. all content from SimpleNight), the message should state that the oder has been submitted and will be confirmed with the vendor.

If the content is buyable (e.g. a sandwich in Bob), the message should state that the order has been confirmed.

If the traveler has a profile set up with us, there should be a link back to GuestApp where the traveler can view the order and its status.

If the traveler does not have a profile set up with GuestApp, there should be a link back to GuestApp to have them set up a profile with us with most info already filled in (given we have all their info in the order).

**Future Considerations**
Things we've considered but are currently out of scope. The considered things if deemed necessary, would be entered in another user story and implemented through that user story.

**Error Messages**
The system should fail gracefully.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
