### ISSUE TITLE
Email confirmation on order backed by vendor

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#114]
As a traveler, I receive an email notification stating details of my order once the order has been confirmed by the vendor, so that I know that the vendor will provide my experience/service.

**Acceptance Criteria**

This email is in the event when the bought item is bookable and has been confirmed by the vendor.

If the traveler has a profile set up with us, there should be a link back to GuestApp where the traveler can view the order and its status.

If the traveler does not have a profile set up with GuestApp, there should be a link back to GuestApp to have them set up a profile with us with most info already filled in (given we have all their info in the order).

**Future Considerations**
Things we've considered but are currently out of scope. The considered things if deemed necessary, would be entered in another user story and implemented through that user story.

**Error Messages**
The system should fail gracefully.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
