### ISSUE TITLE
Medium | Check availability button is not disabled when the selected date is unavailable

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#123]
***Describe the bug***
When the user selects a date for a catalog item that is unavailable, the "Check Availability" button is not disabled and the user is able to proceed with the booking flow

***Steps to reproduce the behaviour:***
1. Launch App
2. Click a catalog item that has unavailable dates (e.g. Day Private Transfer Airport)
3. Select Date that is unavailable

***Expected behaviour***
Check Availability button is disabled

***Actual behaviour***
Check Availability button is not disabled and the user can continue with the flow

***Screenshots***
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/25214171/53254319-22972780-3691-11e9-933d-e75e202ab3fd.gif)

OS: iOS
Build 21 0.3(39)

Additional context

**Comment by kaurmandie** [comment]
Check Availability button is enabled, but if an experience is not available for selected date then it is highlighted in red as "unavailable", and tapping Check Availability user can't continue with the flow.

After selecting the dates when selected experience is available and it has Options/flavour available. Don't select any Option and nd tapping Check Availability user can't continue with the flow but Option "Please select " is highlighted in Red.

**Comment by Justin-Lag** [comment]
No longer applicable with Livn's implementation.  Closing and archiving
