### ISSUE TITLE
Medium| Primary contact name field only accepting letters

### ISSUE THREAD

**Issue by rayojosiah** [Guestlogix/traveler-ios#126]
Version 0.3 Release 22
**Steps:**
1. Navigate to primary contact screen on a booking
2. Enter alphanumeric characters in the first name and last name field.
3. Complete other information and check out

**Actual result:**
1. User gets an error message: Invalid format

**Expected result:**
1. Api allows user to enter alphanumeric characters. This used be allowed on the UI as well.

**Comment by kaurmandie** [comment]
verified in Build 0.0.3(72)
