### ISSUE TITLE
Medium| Added flights are not retained if user force closes app

### ISSUE THREAD

**Issue by rayojosiah** [Guestlogix/traveler-ios#129]
version 0.3 release 22
**Steps:**
1. Add flights
2. Force close the app
3. Open the app back

**Actual result:**
1. User is navigated to the home screen added flights are not retained.

**Expected result:**
1. User should be navigated to the experience screen with added flight screen displayed.

**Comment by kaurmandie** [comment]
Expected behavior .
As discussed with Justin, if the App is closed and launched again the added flight info won't be retained.
