### ISSUE TITLE
Search services catalog

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#136]
As a traveller, I can search for a service, so that I can find something to do with my flight or around airport.

**Acceptance criteria**

* The traveller can enter free text form
* The traveller should choose from flight legs I've already entered
* The traveller can filter on specific experience category to use (e.g. before flight or all)
* The traveller can sort by alphabetical and reverse alphabetical order, as well as pricing on the item item if applicable

**Future considerations**

* The traveller should be able to specify a new flight leg
* Ability to reuse previous searches
* Ability to use popular searches
* Ability to predict what the traveller is typing
* Ability to actively shortlist results based on what the traveller is typing

**Error messages:**

* The system should let the traveller know if there are no searches matching their set criteria. Stretch is that is provides idea on how to make it render results (e.g. category you chose has only 2 items)
* The system should be able to fail gracefully if something goes wrong while fetching results and allow the traveller to retry

**UX considerations:**
see wireframes in the corresponding epic

**Tech considerations:**
TBD

**QA considerations:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
