### ISSUE TITLE
search functionality within the app

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#137]
As a traveller, I can search for functionality with the application that I can'd find through navigation.

**Acceptance criteria**

* The traveller can enter free text form

**Future considerations**

* Ability to reuse previous searches
* Ability to use popular searches
* Ability to predict what the traveller is typing
* Ability to actively shortlist results based on what the traveller is typing

**Error messages:**

* The system should let the traveller know if there are no searches matching their set criteria. Stretch is that is provides idea on how to make it render results
* The system should be able to fail gracefully if something goes wrong while fetching results and allow the traveller to retry

**UX considerations:**
see wireframes in the corresponding epic

**Tech considerations:**
TBD

**QA considerations:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
