### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by godd9170** [Guestlogix/traveler-ios#139]
As a traveller, I view and read the FAQ section so that I can find relevant information I seek in relatively fast manner.

ACCEPTANCE CRITERIA:
- FAQ should be easily found from quick nav bar
- FAQ should be searched by the generic search

FUTURE CONSIDERATIONS/OUT OF SCOPE:
None

UX CONSIDERATIONS:
TBD

TECHNICAL CONSIDERATIONS:
Per Ata, there is a CMS platform that can automatically create FAQ questions/answers.

Potential: ReadMe.io

Need a spike to research which one to utilize.

TEST CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
