### ISSUE TITLE
View flights

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#141]
As a traveller, I view my previously added flights so that I can see what has been saved thus far.

**Acceptance criteria:**
* Traveller can see upcoming vs past flights
* Traveller should be able to go in to see individual flight and its information

**Future considerations:**
* Ability to search for specific flight/leg
* Ability to archive past flights

**Error messages:**
System should fail gracefully in case it can't generate the page, allow the user to retry

**UX considerations:**
TBD

**Tech considerations:**
TBD

**QA considerations:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
