### ISSUE TITLE
View pending order

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#142]
As a traveller, I view a specific order and see if it is pending state as the order has been submitted but not confirmed by the supplier, so that I'm aware of the latest status.

**Acceptance criteria:**

* Up to date status being surfaced back to the user
* Links back to emails on pending and confirmed status of an order (when there is no profile for the traveller)
* The status should have a date stamp explaining when it was last updated

**Future considerations:**
This functionality won't be necessary if the supplier can confirm that they can supply the order on order submission

**Error handling:**
The system should fail gracefully.

**UX requirements:**
TBD

**Tech requirements:**
TBD

**QA requirements:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
