### ISSUE TITLE
Quick profile creation

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#143]
As a traveller, I am prompted to and click on "quick profile creation" once I submit the order.

**Acceptance criteria:**

* User name, email and preferred payment method, as well as address would already be known as they were necessary for order to be placed.
* Ask for preferred password for the new profile
* Ask to double check all the stored info before creation of profile

**Future considerations:**
none

**Error handling:**
The system should fail gracefully.

**UX requirements:**
TBD

**Tech requirements:**
TBD

**QA requirements:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
