### ISSUE TITLE
Access experience catalog item

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#144]
As a traveller, I view experience catalog item that was shared with me via social media, so that I can see what my fellow traveller is considering purchasing

**Acceptance criteria:**

* Traveller should be able to access the shared link via their own application (provided they have the same partner application installed)
* Traveller should be able to access the shared link via web as well (in case they don't have access to our mobile application

**Future considerations:**
Will need to consider if BOB catalog item or Services catalog item should be sharable and if yes, whether a website access can be set up for these as well

**Error handling:**
The system should fail gracefully.

**UX requirements:**
TBD

**Tech requirements:**
TBD

**QA requirements:**
TBD

**Comment by Justin-Lag** [comment]
closed and archived.  long term feature.
