### ISSUE TITLE
gCrew app: up to 20% off discount

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#145]
As a gCrew traveller, I enjoy an up to 20% discount on a given experience catalog item, so that I'm encouraged to explore, buy and provide feedback on it.

**Acceptance criteria:**

* Traveller should know what the discount is (how much they are saving)
* Initial thought that the discount is applied in waiving the GLX and 3rd party experience content provider's fee. There is no partner fee as this app won't be associated with an airline.
* MVP could simply show the amount saved and record it for Finance department to be able to reimburse manually at end of the month.

**Future considerations:**
Will need to consider if BOB catalog item or Services catalog item would have any discounts applicable to them.

**Error handling:**
The system should fail gracefully.

**UX requirements:**
TBD

**Tech requirements:**
TBD

**QA requirements:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
