### ISSUE TITLE
gCrew app: $1000 CAD credit

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#146]
As a gCrew traveller, I enjoy an up to a total sum of $1000 CAD credit on a given experience catalog items, so that I'm encouraged to explore, buy and provide feedback on it.

**Acceptance criteria:**

* Traveller should know what how much of the credit I've used and on what
* MVP could simply record traveller's usage in a report and supply to Finance department to be able to reimburse manually at end of the month.

**Future considerations:**
Will need to consider if BOB catalog item or Services catalog item would have any discounts applicable to them.

**Error handling:**
The system should fail gracefully.

**UX requirements:**
TBD

**Tech requirements:**
TBD

**QA requirements:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
