### ISSUE TITLE
Home page 2.0

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#151]
child of guestlogix/traveler-ios#210

As a traveller, when I navigate to the home page, I can see content pertaining to my current location and upcoming flight so that I can start/continue planning my stress free journey.

**Acceptance criteria:**
linked to #6 (home page 1.0)

* same algorithm for viewing current city + promoted cities experience content if no flights have been added, else the user sees flight legs added + promoted cities experience.
* there are two rows of tumblers going from left to right chronologically (as opposed to top to bottom as in home page 1.0)
* the flight icon provides flight info, before flight services, BOB and after flight services categories.

more info here:
https://drive.google.com/open?id=1yY2ax8LhwK-r7Wc7bF5hheKz1PtDqDAsnNf8JbYBY7I

**Future considerations:**
TBD

**Error handling:**
The system should fail gracefully.

**UX requirements:**
TBD

**Tech requirements:**
TBD

**QA requirements:**
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
