### ISSUE TITLE
Livn | Quantity picker updates

### ISSUE THREAD

**Issue by Justin-Lag** [Guestlogix/traveler-ios#158]
Child of guestlogix/traveler-ios#156
Depends on guestlogix/guest#214

As a traveler I want to be restricted from entering more tickets than I can order at once (10) so that I'm not submitting an order that would be rejected

**Acceptance Criteria**
1. 10 tickets maximum can be ordered at once (**TBD** if this is 10 for adults/children each or combined) <- This check will come from the API
1. Display the flavour name
1. Terms and conditions prompt is removed

**Out of scope/Future consideration**
Any relevant out of scope items

**UX if needed**
***Design:*** https://zpl.io/bljENX0
*Tag:* LIVN

https://www.notion.so/Livn-Buy-Flow-7f7c6be982804354a2437ce90db2911f

**Technical details if needed**
[API]

**Testing considerations**
- The "Max 10 tickets" will not be implemented yet because we do not get that data from backend.
- When the user selects more than 10 tickets, the error message does not tell the user it's because there is a max 10 ticket requirement. We currently do not consider informative error handling

**Comment by Mariakani** [comment]
verify with iOS build version  0.3(61)
