### ISSUE TITLE
Livn | Order confirmation

### ISSUE THREAD

**Issue by Justin-Lag** [Guestlogix/traveler-ios#160]
Child of guestlogix/traveler-ios#156

As a traveler I want to have a way to view the ticket for my purchase and have the ticket emailed to me so that I can attend the experience

**Acceptance Criteria**
1. Display;
* Experience name
* date and time ~of the booking~ of the event taking place
~* order number~
* instruction that tickets would be sent to the primary email and display the email
1. The ticket for the experience I purchased is;
For MVP, we've deferred viewing the ticket within the app and will just mention the ticket has been emailed to them.
~* The ticket is viewable in PDF via the app~
~* accessible by GLX from their stories~

**Out of scope/Future consideration**
Any relevant out of scope items

**UX if needed**
***Design:*** https://zpl.io/V0qDEyQ
*Tag:* LIVN

https://www.notion.so/Livn-Buy-Flow-7f7c6be982804354a2437ce90db2911f

**Technical details if needed**
[DB]
[API]

**Testing considerations**

**Comment by dorothyfu** [comment]
All features are implemented in pr #224 except the actual functionality of "Email Ticket" button

**Comment by Justin-Lag** [comment]
closed and archived.  no longer needed
