### ISSUE TITLE
Profile | View profile - MVP

### ISSUE THREAD

**Issue by Justin-Lag** [Guestlogix/traveler-ios#163]
child of guestlogix/traveler-ios#55

As a traveler I want see my user profile so that I can confirm my details available within the app

**Acceptance Criteria**
1. The profile is accessible from the home page
1. The profile will display the travelers name, email address ~, and saved payment info if available~
~1. There is a link for editing the profile~
1. There's a link to order page
1. There is a link for the app settings

**Out of scope/Future consideration**
Any relevant out of scope items

**UX if needed**
- https://app.zeplin.io/project/5bc0d5e9e2c97b18e1537de2/dashboard?tag=Home%20page
- https://app.zeplin.io/project/5bc0d5e9e2c97b18e1537de2/dashboard?tag=Profile

**Technical details if needed**

### Request
_e.g. `GET /example/{id}?query=xyz&also=xyz`

**Body**
```
{ "test : "this" }
```

### Response
**Body**
```
{ "test : "this" }
```

**Status Codes**
_e.g. 200 Success_

## Service
_e.g. Business logic in this layer_

## Repository
_e.g. Data access logic in this layer_

## Database
_e.g. Database specific concerns_

**Tables**
_e.g. Account_Traveler_

**Columns**
_e.g. Date Created_

**Testing considerations**

**Comment by dorothyfu** [comment]
Testing instructions:
- There is currently a known bug where the name does not appear when the user kills the app and reopens it. This is because we do not persist the profile data yet.

**Comment by kaurmandie** [comment]
Verified in 0.3(72)
Able to login successfully using Gcrew account from the Home screen
