### ISSUE TITLE
Profile | View app settings - MVP

### ISSUE THREAD

**Issue by Justin-Lag** [Guestlogix/traveler-ios#165]
child of guestlogix/traveler-ios#55

As a traveler I want see application information so that I can have better understanding of what is available in the app and how to use it

**Acceptance Criteria**
1. Accessible from the profile page
1. Display link to Legal information **Need COPY**
1. Display link to Privacy Policy **Need Copy**
1. Display trigger to sign out of profile 
~1. Display trigger to deleting profile~
1. Display app version

**Out of scope/Future consideration**
Any relevant out of scope items

**UX if needed**
- https://app.zeplin.io/project/5bc0d5e9e2c97b18e1537de2/dashboard?tag=Profile

**Technical details if needed**

### Request
_e.g. `GET /example/{id}?query=xyz&also=xyz`

**Body**
```
{ "test : "this" }
```

### Response
**Body**
```
{ "test : "this" }
```

**Status Codes**
_e.g. 200 Success_

## Service
_e.g. Business logic in this layer_

## Repository
_e.g. Data access logic in this layer_

## Database
_e.g. Database specific concerns_

**Tables**
_e.g. Account_Traveler_

**Columns**
_e.g. Date Created_

**Testing considerations**

**Comment by Justin-Lag** [comment]
@dorothyfu fyi - i removed the acceptance criteria for Deleting a profile

**Comment by dorothyfu** [comment]
@Justin-Lag I'll remove the button

**Comment by kaurmandie** [comment]
verified - 

Setting link is available under Profile. Tapping on it navigates to the Settings screen and it has :
Legal Info
Privacy Policy
App Version
SignOut button : Selecting it triggers a message "Are you sure to sign out of you profile" with Ok and cancel button. If user selects OK then Sign-out is successful
