### ISSUE TITLE
Minor | Order confirmation screen does not reflect mocks

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#173]
**Describe the bug**
1. x button at the top right should not be there. Instead, exit button should be a "home" button at the bottom of the screen
2. Missing checkmark image

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to the order confirmation screen

**Actual result**
Missing "home" button and checkmark image

**Expected behaviour**
The screen reflects the mocks

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-03-22 at 10 59 05](https://user-images.githubusercontent.com/25214171/54831870-895c3080-4c91-11e9-9170-c81984808b27.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 0.3(45)

**Additional context**

**Comment by kaurmandie** [comment]
X sign is not available on the Order Confirmed screen.
Home button is available and tapping on it navigates to Catalog home screen.

Closing this issue, there are still  more changes required on the Order confirmation screen  and will be tested in different ticket
