### ISSUE TITLE
Minor | Product name extends into price when it is too long

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#174]
**Describe the bug**
Product text overlaps price text when the product name is too long

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch app
2. Go through the order flow and navigate to the "Review your order" screen

**Actual result**
Pass names overlap the price when it is too long

**Expected behaviour**
- Title + Subtitle should truncate after 1 line (verified with Dorian) and not overlap the price

**Screenshots**
![Simulator Screen Shot - iPhone X - 2019-03-22 at 11 18 13](https://user-images.githubusercontent.com/25214171/54833296-35068000-4c94-11e9-9c54-71bc692c2857.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 0.3(45)

**Additional context**

**Future Considerations**
- Currently we are truncating the title and subtitle after 1 line because word wrap will cause the text fields to get pushed out of bounds.
- Since this is the last screen before the user places their order, the truncation may omit important information for the passes. Right now, the pass names we see are short enough (e.g. adult, child) that this does not cause an issue. However, livn's prod may have longer pass names or localization may cause the pass names to increase in size.

**Comment by dorothyfu** [comment]
Apr 8, 2019 : Not testable yet because the screens after booking questions do not work yet

**Comment by dorothyfu** [comment]
Testable on 0.3(64). The messed up layout will be fixed in #224

**Comment by dorothyfu** [comment]
![Simulator Screen Shot - iPhone X - 2019-04-26 at 10.43.52.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c2cdeb240332e0012a78bf2/125516c66e82c728ace21e0d46db9d97368e82bd80fbff70a74ff5912706147b2610e366308cd320b04c7e41374f53bc43585e4de1f98d36a4b02c21ce4c0aedcf695c6ac33f03b0aac25de05bef73cf5d8fa4b9d81ac4ba3b25e18e8c196d1951188afb5a35a7cb48c90ae457f30f04fa47693ebf3c633e559e0c7424616623aefadd5e8e8d67a4bc17294485.png)

**Comment by Mariakani** [comment]
test Data is not available.

As per above  screenshot from mock Api/ emulators , it looks good. So moving this ticket to PM review
