### ISSUE TITLE
Add .quantity question type

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#177]
**Description**
This question type asks for an integer

**Acceptance Criteria**
- Quantity picker looks the same as the passes quantity picker
- Takes in integers 
- Default number: 0
- Increment by 1
- ~~Space between "+" and "-" needs to be clickable so user can type in a number~~

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
There are currently no quantity type questions on livn since this was a simplenight change. QA will have to test on the mock api.

**Future Considerations**
Under simplenight, quantity may have a price attached to it because the examples that were available were add on items that you can add to your experience. For example, adding a pack of cigarettes to your show ticket. Because Livn does not use the quantity type, no price logic was added to this question type. We will also need to consider if we want to put add on items with price on the questions screen since it only deals with purely informational questions (when/if we decide to use simplenight again)

**Comment by Mariakani** [comment]
verified with iOS build version 0.3(66)
