### ISSUE TITLE
Add .date question type

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#178]
**Description**
This question type asks the user to select a date (e.g. birthday)

**Acceptance Criteria**
- Use the same date picker as the one in catalog details
- Default date is today
- We will require backend to send us min and max date (e.g. user cannot select a date in the future for birth date) - NOT IMPLEMENTED YET
- If there are multiple date questions, only one date picker can be open at a given time

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Mariakani** [comment]
verified with iOS build version  0.3 (66)
