### ISSUE TITLE
Minor | Questions form row disappears 

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#183]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch app
2. Navigate to the questions screen
3. Leave the first field blank
4. Click "Checkout"
5. Type something into the first field
6. Click "Checkout"
7. Scroll back to the first field

**Actual result**
Row disappears

**Expected behaviour**
Row is visible with the typed in answer

**Screenshots**
![ezgif com-video-to-gif (5)](https://user-images.githubusercontent.com/25214171/55107247-3b876400-50a7-11e9-9eb0-f29207f399fd.gif)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 0.3(47)

**Additional context**

**Comment by kaurmandie** [comment]
issue not replicable in 0.3(72)
