### ISSUE TITLE
Major | Only 1 child and 1 adult pass is requested 

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#188]
**Describe the bug**
Regardless of how many passes the user selects on the passes screen, only 1 adult and 1 child pass is requested to the questions endpoint.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch app
2. Navigate to the passes screen
3. Add a bunch of passes

**Actual result**
Only 2 passes are requested in the url (https://guest-traveler-api-develop.guestlogix.io/product/03-01-005-9983/question?pass-ids=0320190331005000049984Adult&pass-ids=0320190331005120049984Child)

**Expected behaviour**
Number of passes requested reflects the amount of passes chosen in the passes screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 0.3 (47)

**Additional context**

**Comment by Mariakani** [comment]
verified with iOS build version 0.3 (66)
