### ISSUE TITLE
Minor | "Date Unavailable" row does not update 

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#196]
Requires #181

**Describe the bug**
Date row does not update back to selected date when the user goes from an unavailable date to an available date

**To Reproduce**
Steps to reproduce the behaviour: (found the bug on homepage 2D Great Ocean Road experience)
1. Launch the app
2. Click on an experience that has both available and unavailable dates
3. Select an available date
4. Select an unavailable date

**Actual result**
After the user selects an unavailable date, the datepicker automatically goes back to the previously available date. The "Date" row still displays "unavailable" despite the date being available

**Expected behaviour**
After the user selects an unavailable date, the datepicker automatically goes back to the previously available date. The "Date" row displays the selected date's date

**Screenshots**
![ezgif com-video-to-gif (6)](https://user-images.githubusercontent.com/25214171/55437490-024e6880-556d-11e9-94d6-37feee29c665.gif)

**Desktop (please complete the following information):**
 - OS: iOS
- https://github.com/Guestlogix/traveler-ios/pull/193

**Additional context**

**Comment by kaurmandie** [comment]
1)Select date when experience is available
2)Select date when experience is not available and Message is displayed "Unavailable"
3)Change the date to the same selected at step1 and Unavailable message is no longer displayed now
