### ISSUE TITLE
Medium | No prompt for user to select an option

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#197]
**Describe the bug**
After the user selects an available date on the experience details screen, the option row appears and the user can click "check availability". If no option is selected, there is no feedback for the user to select an option

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch app
2. Navigate to a catalog item details with available dates
3. Select an available date
4. Click "Check availability"

**Actual result**
Nothing happens, user is not navigated to the passes screen and no error is displayed

**Expected behaviour**
User is prompted to select an option

**Screenshots**
![ezgif com-video-to-gif (7)](https://user-images.githubusercontent.com/25214171/55485117-c44a5680-55f7-11e9-99f7-7789a09d30e6.gif)

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 0.3(49)

**Additional context**

**Comment by Mariakani** [comment]
verified with iOS build version 0.3 (68)

**Comment by kaurmandie** [comment]
Verified in iOS build v 0.3(68) , When check availability is tapped without selecting any Options then user is notified 'Please select' an option ( highlighted in Red) "
