### ISSUE TITLE
Medium| Remove the displayed experience cap from 5

### ISSUE THREAD

**Issue by rayojosiah** [Guestlogix/traveler-ios#215]
**Actual result:**
1. Experience displayed are capped at 5.

**Expected result:**
1. Can this restriction be removed.
This would enable us test the impact of having more than 5 as well as real world scenario.

**Comment by dorothyfu** [comment]
Testing instructions:
- Please verify that the number of experiences the API returns is the same number of experiences displayed in the carousel

**Comment by Mariakani** [comment]
verify with iOS build version 0.3(61)
