### ISSUE TITLE
Entire "Flight Number" row should be selectable

### ISSUE THREAD

**Issue by dorothyfu** [Guestlogix/traveler-ios#217]
**Description**
Currently, the text field only gets selected if you click the right side of the row, but the entire row should be clickable as per @Do-Jones 

**Acceptance Criteria**
Textfield is selectable no matter where on the row you click

**Error Messages**
Any error messages that should be expected for invalid usage.

**UX Requirements**
Mockups, wireframes or any notes pertaining to the UX.

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
