### ISSUE TITLE
What to display when there's nothing in the catalog

### ISSUE THREAD

**Issue by Justin-Lag** [Guestlogix/traveler-ios#218]
**STUB**

How do we handle the scenario when there's nothing in the catalog for a destination

**Comment by willmero** [comment]
Might be controversial, but if there is nothing in the catalog from our partners that we will gain commission on, it might be better to display items from a public more plentiful source like tripadvisor or another service that we might not be able to make commission on, but will still be able to show SOMETHING to the user. We would just favour our content when there is something in the catalog.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
