### ISSUE TITLE
Medium | Only questions for one adult ticket are presented

### ISSUE THREAD

**Issue by Mariakani** [Guestlogix/traveler-ios#220]
**Describe the Bug**

When a user want to create an order of more than one adult tickets, only questions for one adult are presented.

**To Reproduce the bug**
1. launch traveler app -ios
2. Add a flight say AC862 of any current or future date
3. Select any experience items and navigate to date picker and select a date when the experience is available
4. tap on the check availability button
5. Keep the child or infants ticket at 0 if there are ones and increase the quantity of adult tickets to 2 or more
6. Tap book now button and the observe the questions present on the next page

**Actual Result**
Only questions for one adult are presented

**Expected Result**
All questions for the quantity number of tickets selected should be presented

blocks #188

**Comment by dorothyfu** [comment]
Not a bug, verified with @Mariakani

**Comment by Mariakani** [comment]
This is not  a bug anymore
