### ISSUE TITLE
Add to wishlist

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#31]
As a traveller, I mark a catalog item to be added to my wishlist, so that I can come back to it when I'm ready to review/buy.

ACCEPTANCE CRITERIA:
1. The user should be able to specify what wishlist to add the item to
2. If the user doesn't have wishlist set up, then the set up wishlist story should kick in

FUTURE CONSIDERATIONS:
none

ERROR MESSAGES:
- The system should fail gracefully if the traveller for some reason could not add the item to their wishlist
- In the above case, the traveller should be able to resubmit the item to be added to the wishlist

UX REQUIREMENTS:
TBD

TECH REQUIREMENTS:
TBD

QA REQUIREMENTS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
