### ISSUE TITLE
Epic: wishlists iOS

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#45]
This is a collection of stories pertaining to wishlists. The user should be able to:

parent of #46 (create a wishlist)
parent of #48 (delete a wishlist)
parent of #49 (rename a wishlist)
parent of #31 (add an item to a wishlist)
parent of #47 (delete an item from a wishlist)

Future considerations/out of scope:
parent of #50 (share wishlist with another user)

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
