### ISSUE TITLE
Create a wishlist

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#46]
As a traveller, I create a new wishlist so that I can earmark items to be saved for further browsing/purchasing later.

ACCEPTANCE CRITERIA:
- should be able to create a wishlist on its own
- should be able to create a wishlist if trying to add an item to a wishlist
- items to be added to a wishlist will be experience ones, later on we'll add upgrades and tangible on board bought items
- all wishlists will be private by default

ERROR MESSAGES:
The system should fail gracefully if it is not able to create a wishlist and let the user retry.

If the user tries to create a wishlist with a name that they already have, the system should add a character at the end of the name and create it anyways. E.g. Dallas trip vs Dallas trip1

FUTURE CONSIDERATIONS:
- Ability to designate wishlists as private or public

UX CONSIDERATIONS:
TBD

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
