### ISSUE TITLE
Delete item from wishlist

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#47]
As a traveller, I remove an item from the wishlist so that I no longer am reminded of it.

ACCEPTANCE CRITERIA:
The traveller should be able to remove an item from wishlist either when browsing the item's detail page or when looking at the overall wishlist

FUTURE CONSIDERATIONS:
none

ERROR MESSAGES:

The system should fail gracefully if the traveller for some reason could not delete the item to their wishlist
In the above case, the traveller should be able to resubmit the item to be added to the wishlist

UX REQUIREMENTS:
TBD

TECH REQUIREMENTS:
TBD

QA REQUIREMENTS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
