### ISSUE TITLE
Delete a wishlist

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#48]
As a traveller, I delete a wishlist as I no longer need it.

ACCEPTANCE CRITERIA:
- need to make sure there is a confirmation for deletion or an ability to undo once deleted

FUTURE CONSIDERATIONS:
- May want to be able to "resurrect" wishlists that were deleted

ERROR MESSAGES:
The system should fail gracefully if it is not able to delete a wishlist and let the user retry.

UX CONSIDERATIONS:
TBD

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
