### ISSUE TITLE
Rename a wishlist

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#49]
As a traveller, I rename a wishlist so that it can better reflect the collection of items it has.

ACCEPTANCE CRITERIA:
- the traveller should not be able to provide a new name that is longer than what we could store

ERROR MESSAGES:
The system should fail gracefully if it is not able to rename a wishlist and let the user retry.

If the user tries to rename a wishlist with a name that they already have, the system should add a character at the end of the name and create it anyways. E.g. Dallas trip vs Dallas trip1

FUTURE CONSIDERATIONS:
none

UX CONSIDERATIONS:
TBD

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
