### ISSUE TITLE
share wishlist with another user

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#50]
As a traveller, I share a wishlist with another user that I can grant modify access to the list by that user

ACCEPTANCE CRITERIA:
- should be able to share with another traveller (use the traveller's log in user name/email)
- specify if the other traveller can only view or modify the list as well

ERROR MESSAGES:
The system should fail gracefully if it is not able to share the wishlist and let the user retry.

FUTURE CONSIDERATIONS:
none

UX CONSIDERATIONS:
TBD

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
