### ISSUE TITLE
Create profile

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#53]
As a traveller, I create a profile for myself, so that I can keep track of my orders, wishlists and preferred payment method.

ACCEPTANCE CRITERIA:

- Should be able to do this with utilizing social media: Google, Facebook, Twitter, LinkedIn

- Gather the following information about the traveller: email address to be used as user id, password, first name, last name

- Additional information that would be associated with profile: user photo, preferred payment method, preferred language, preferred currency, past orders, wishlists [these will be fleshed out in separate stories]

FUTURE CONSIDERATIONS:
add journeys associated with profile

ERROR MESSAGES:

The system should fail gracefully if it can't create a profile and let the traveller retry

UX CONSIDERATIONS:
TBD

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
