### ISSUE TITLE
Profile | log in

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#56]
child of guestlogix/traveler-ios#55

Depends on guestlogix/guest#215

As a GLX team member I want to log in using my guestlogix gmail account  so that I can have secure access to the GCrew platform

**Acceptance Criteria**
1. GLX team member can log in from the profile page with the MVP
1. GLX team member must have successfully passed the Gmail authentication
1. On successful log in, the user remains on the profile page and will see the logged in state
1. A user stays logged in until manually logging out
1. Only GLX email domains are accepted

**Out of scope/Future consideration**
Any relevant out of scope items

**UX if needed**
***Designs:***
https://zpl.io/aXP57Kj
*Tags: Profile*

**Technical details if needed**

### Request
_e.g. `GET /example/{id}?query=xyz&also=xyz`

**Body**
```
{ "test : "this" }
```

### Response
**Body**
```
{ "test : "this" }
```

**Status Codes**
_e.g. 200 Success_

## Service
_e.g. Business logic in this layer_

## Repository
_e.g. Data access logic in this layer_

## Database
_e.g. Database specific concerns_

**Tables**
_e.g. Account_Traveler_

**Columns**
_e.g. Date Created_

**Testing considerations**
1. No concerns with syncing GLX gmail passwords.  ie: if i change the password my secure session within the gcrew app remains

**Comment by kaurmandie** [comment]
Verified in 0.3(72)
Able to login successfully using Gcrew account from the Home screen
User remains signed in
Selecting sign out button, the user is no longer logged into their profile
Able to switch between multiple Guestlogix emails and login and logout successfully
