### ISSUE TITLE
Profile | log out

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#57]
child of guestlogix/traveler-ios#55

As a GLX Crew member I want to exit the secure session so that my personal information is not accessible from the device

# Acceptance Criteria
1. Log out prompt is within the settings
1. After confirmation, the user will redirected home page
1. Logging out will make all personal information inaccessible from the device
1. All personal info associated with the user is removed.  includes personal info, orders, flights.

**Out of scope/Future consideration**
Any relevant out of scope items

FUTURE CONSIDERATION:
none

ERROR MESSAGES:
If system fails to log the user out, do so gracefully and let the user retry.

UX CONSIDERATIONS:
***Designs:*** https://zpl.io/anpk36J
*Tags:* Profile
TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closed and completed
