### ISSUE TITLE
update profile

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#58]
As a traveller, I can update my profile, so that it contains the latest information.

ACCEPTANCE CRITERIA:

Should be able to update:
- first name
- last name
- user id
- password
- preferred payment method (stored billing address and payment method credentials, i.e. card number, expiration date, cvs number, card holder's name)

FUTURE CONSIDERATIONS:
- user photo
- preferred language
- preferred currency

ERROR MESSAGES:
The system should fail gracefully if it can't let the traveller update the profile and let the traveller retry

UX CONSIDERATIONS:
**Designs:** https://zpl.io/a7Od1WE
*Tags:* Profile, Update profile

***Notion:*** https://www.notion.so/Edit-Profile-325324ce1a0b4817b9f2bb59e58ec9cb

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
