### ISSUE TITLE
Profile | delete profile

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#59]
As a traveller, I can delete my profile if I no longer want to have a profile on the system.

ACCEPTANCE CRITERIA:
- need to ensure the traveller confirms they want to delete the profile
- have an option of putting the profile in inactive mode instead of delete it

FUTURE CONSIDERATIONS:
none

ERROR MESSAGES:
The system should fail gracefully if it can't let the traveller delete the profile and let the traveller retry

UX CONSIDERATIONS:
**Designs:** https://zpl.io/VqWYNYl
*Tags:* Profile, Delete profile

Notion: https://www.notion.so/Delete-Profile-f9444e301db84172bd616f61646d6e9b

***Please Note:  For MVP release the user can delete a profile, archiving a profile would be a feature we would need to re-visit.***

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
