### ISSUE TITLE
search order within specific timeframe

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#61]
As a traveller, I view an order I've made, so that I know what I bought and its progress.

ACCEPTANCE CRITERIA:
- allow the user to specify the time frame for the orders that they are looking for (last month, last 3 months, last 6 months, or start-end date)

FUTURE CONSIDERATIONS:
none

ERROR MESSAGES:
The system should fail gracefully if it can't show the orders in the timeframe (something went wrong) and let the traveller retry

If there were no orders in the timeframe specified, show that no orders were made during this time.

UX CONSIDERATIONS:
TBD

TECH CONSIDERATIONS:
TBD

QA CONSIDERATIONS:
TBD

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
