### ISSUE TITLE
Persist flight on app shutdown

### ISSUE THREAD

**Issue by godd9170** [Guestlogix/traveler-ios#76]
**Description**
When a user picks a flight, and it's added to the top of the home screen, exiting and closing the app will remove the flight.

This flight should persist despite the close of the app.

Deleting + Re-installing the app is not required to persist.

**Acceptance Criteria**
1) Add a flight
2) Close the app
3) re-open the app and see that the flight is still at the top of the home screen.

**Error Messages**
Unable to persist flight.

**UX Requirements**
N/A

**Tech Requirements**
Local data store: @ata-n to clarify.

**QA Requirements**
Closing the app should not cause the flights to disappear.

**Comment by Justin-Lag** [comment]
Closing.  this will not be provided by the SDK and should be implemented by the apps
