### ISSUE TITLE
Minor| Back button not getting displayed on availability screen

### ISSUE THREAD

**Issue by rayojosiah** [Guestlogix/traveler-ios#81]
Release 11 (v0.2)
https://www.useloom.com/share/e49159a958b7471793b095b8aedede51
**Steps:**
1. User on home screen
2. Tap on experience
3. Navigate to the availability screen (screen to add ticket)
4. Tap back button
5. Close the exprience page
6. Open again
7. Navigate to the availability screen (screen to add ticket)
8. Observe

**Actual result:**
1. Back button is not displayed. As can be seen in attached video link
2. This is just one scenario

**Expected result:**
1. UI consistency,
2. Back button should be displayed.

**Comment by kaurmandie** [comment]
Issue not replicable in Build - 0.3(72) 
Back button is displayed on the pass selection screen.
