### ISSUE TITLE
Submitted order

### ISSUE THREAD

**Issue by vbereg** [Guestlogix/traveler-ios#97]
As a traveller, I see a message explaining that my order has been submitted and whether it is already confirmed or not, so that I know the status of my order.

links to #44 

**Acceptance Criteria**
1. If the content is bookable (e.g. all content from SimpleNight), the message should state that the oder has been submitted and will be confirmed with the vendor.

2. If the content is buyable (e.g. a sandwich in Bob), the message should state that the order has been confirmed.

**Error Messages**
The system should fail gracefully.

**UX Requirements**
Order Pending: https://zpl.io/bzA5QJ7
https://zpl.io/beo9gRD

Order Confirmed: https://zpl.io/VDq6yKr

Order Cancelled: (Under Review) https://zpl.io/2EP6MWy
(Cancelled) https://zpl.io/bPX5kgm

**Tech Requirements**
Design patterns, naming conventions, or any other considerations for the developer.

**QA Requirements**
What the QA should be testing for when evaluating this feature.

**Comment by Justin-Lag** [comment]
closing and archiving. Will re-open in Jira when this feature gets prioritized
